apiVersion: apps/v1
kind: Deployment
metadata:
  name: documentation
  namespace: vibe-social
spec:
  selector:
    matchLabels:
      app: documentation
  template:
    metadata:
      labels:
        app: documentation
    spec:
      containers:
        - name: documentation
          image: vibesocial/documentation
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1.0"
              memory: "1000Mi"
            requests:
              cpu: "0.75"
              memory: "500Mi"
