apiVersion: v1
kind: Service
metadata:
  name: documentation
  namespace: vibe-social
  labels:
    app: documentation
spec:
  type: ClusterIP
  selector:
    app: documentation
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8080
